# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                         Copyright (C) 2014 Chuan Ji                         #
#                             All Rights Reserved                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
"""Main web app server library."""

import json
import flask

from lib import asciidoc_lib
from lib import env_lib


# The WSGI app object.
app = flask.Flask(__name__)


@app.route('/asciidoc-to-html', methods=['POST'])
def AsciiDocToHtml():
  """Handler for AsciiDoc to HTML conversion.

  POST arguments:
    - text: the text to convert.
  Returns:
    A JSON dict of the form:
        {
          'success': <A boolean indicating whether the conversion succeeded.>
          'html': <HTML generated by AsciiDoc>
          'error_message': <Warnings or error messages>
        }
  """
  text = flask.request.form.get('text', '')
  (asciidoc_return_code, asciidoc_stdout, asciidoc_stderr) = (
      asciidoc_lib.RunAsciiDoc(text))
  response = {
      'success': asciidoc_return_code == 0,
      'html': asciidoc_stdout,
      'error_message': asciidoc_stderr,
  }
  return json.dumps(response)
