# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                         Copyright (C) 2014 Chuan Ji                         #
#                             All Rights Reserved                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
"""Main web app server library."""

import flask
import json

from lib import asciidoc_lib
from lib import env_lib


# The WSGI app object.
# pylint: disable=invalid-name
app = flask.Flask(
    __name__,
    template_folder=env_lib.TEMPLATES_DIR,
    static_folder=env_lib.STATIC_DIR)
# pylint: enable=invalid-name


@app.route('/')
def RenderHome():
  return flask.render_template('home.html')


@app.route('/api/v1/asciidoc-to-html', methods=['POST'])
def AsciiDocToHtml():
  """Handler for AsciiDoc to HTML conversion.

  POST arguments:
    - text: the text to convert.
  Returns:
    A JSON dict of the form:
        {
          'success': <A boolean indicating whether the conversion succeeded.>
          'html': <HTML generated by AsciiDoc>
          'error_message': <Warnings or error messages>
        }
  """
  text = flask.request.form.get('text', '')
  (asciidoc_return_code, asciidoc_stdout, asciidoc_stderr) = (
      asciidoc_lib.RunAsciiDoc(text))
  response = {
      'success': asciidoc_return_code == 0,
      'html': asciidoc_stdout,
      'error_message': asciidoc_stderr,
  }
  return json.dumps(response)
